### ISSUE TITLE
Create a form to import existing lists

### ISSUE THREAD

**Issue by olbat** [ws-armory/ws-armory.github.io#8]
Create a form to import existing lists of (_equipment_slot_,_equipment_name_) in different formats (YAML,JSON,CSV,...).

An example (YAML):

``` yaml

---
Chest:
  - Modest Blast Suit
  - Another Chest
Legs    : 
  - Justicebringer Greaves
Feet:
  - Survivalist's Stompers
#...
```
